# Generated by Django 5.1 on 2024-09-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_slug',
        ),
    ]
