# Generated by Django 5.1 on 2024-09-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactq_name', models.CharField(max_length=50)),
                ('contactq_email', models.CharField(max_length=50)),
                ('contactq_phone', models.CharField(max_length=10)),
                ('contactq_website', models.CharField(max_length=100)),
                ('contactq_message', models.TextField()),
            ],
        ),
    ]
